# Generated by Django 4.0.4 on 2022-05-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('creation_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_daily_notes_backend_app.date')),
            ],
        ),
    ]
